name: Trigger auto deployment for helloworld

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/helloworld-AutoDeployTrigger-53acf303-2ce7-47aa-877f-e2f2d7a79f73.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: dockerimageshosting.azurecr.io
          username: ${{ secrets.HELLOWORLD_REGISTRY_USERNAME }}
          password: ${{ secrets.HELLOWORLD_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dockerimageshosting.azurecr.io/helloworld:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLOWORLD_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n helloworld -g containerapps-workshop --server dockerimageshosting.azurecr.io --username  ${{ secrets.HELLOWORLD_REGISTRY_USERNAME }} --password ${{ secrets.HELLOWORLD_REGISTRY_PASSWORD }}
            az containerapp update -n helloworld -g containerapps-workshop --image dockerimageshosting.azurecr.io/helloworld:${{ github.sha }}
